import { TI18nKeys } from './types';

const resource: Record<TI18nKeys, string> = {
  'app-download': 'Download',
  'app-error_refresh': 'Refresh',
  'app-error_page_error': 'Internal Server Error',
  'app-feedback': 'Feedback',
  'app-settings': 'Settings',
  'app-title': 'Mania Render WebSite',
  'app-mode_enhance': 'Enhance Mode',
  'app-mode_simple': 'Simple Mode',
  'btn-generate': 'Generate Now!',
  'current-language': 'English',
  'main-drag_upload_text': 'Click or drag file to this area to upload',
  'main-upload_bgm': 'Click or drag file to this area to upload your bgm',
  'main-upload_bgm_hint': 'Support all file types which osu and malody supported',
  'main-upload_map': 'Click or drag file to this area to upload your maps',
  'main-upload_map_hint': 'Support .osz, .osu, .mcz, .mc and .zip files',
  'main-upload_replay_placeholder': 'Click or drag file to this area to upload your replays',
  'main-upload_replay_placeholder_hint': 'Support .osr and .mr files',
  'modal-error_file_size_over_max': 'File size can not over 100MB',
  'modal-error_title': 'Error!',
  'modal-finished_title': 'Finished',
  'modal-generate_close_confirm_cancel_text': 'Cancel',
  'modal-generate_close_confirm_content': 'Close the dialog then the generating replay video progress will be abort, are you sure to close the dialog?',
  'modal-generate_close_confirm_ok_text': 'I confirm',
  'modal-generate_close_confirm_title': 'Are you sure to close?',
  'modal-generating_title': 'Generating...',
  'modal-ok_text': 'OK!',
  'settings-fps': 'FPS',
  'settings-platform': 'Malody Platform',
  'settings-speed': 'Speed',
  'settings-video_height': 'Video Height',
  'settings-video_width': 'Video Width',
  'status-current_audio_name_label': 'Audio file',
  'status-current_file_name_label': 'Replay file',
  'status-current_in_queue': 'Current in Queue',
  'status-current_map_name_label': 'Map file',
  'status-current_settings': 'Current Settings',
  'status-current_status': 'Current status',
  'status-current_warning_audio_not_match': 'The audio file maybe is not match the map file',
  'status-current_warning_label': 'Warning',
  'status-current_warning_replay_not_match': 'The replay file maybe is not match the map file',
  'status-download_button': 'Download!',
  'status-generate_generating_introduction': 'Generating...   Please do not close or refresh the dialog and page.',
  'status-generate_progress_label': 'Generate Progress',
  'status-generate_status_error': 'Error!',
  'status-generate_status_finish': 'Finished',
  'status-generate_status_processing': 'Processing',
  'status-generate_status_queue': 'In Queue',
  'status-generate_status_unknown': 'Waiting',
  'status-generate_success': 'Generate Success, click button to download.',
};

export const en = {
  translation: resource,
};
