export type TI18nKeys =
  'app-download' |
  'app-error_refresh' |
  'app-error_page_error' |
  'app-feedback' |
  'app-settings' |
  'app-title' |
  'app-mode_enhance' |
  'app-mode_simple' |
  'btn-generate' |
  'current-language' |
  'error-error' |
  'error-beatmap_not_found' |
  'error-render_failed' |
  'error-replay_invalid' |
  'error-beatmap_invalid' |
  'error-time_exceeded' |
  'main-drag_upload_text' |
  'main-upload_bgm' |
  'main-upload_bgm_hint' |
  'main-upload_map' |
  'main-upload_map_hint' |
  'main-upload_replay_placeholder' |
  'main-upload_replay_placeholder_hint' |
  'modal-error_file_size_over_max' |
  'modal-error_title' |
  'modal-finished_title' |
  'modal-generate_close_confirm_cancel_text' |
  'modal-generate_close_confirm_content' |
  'modal-generate_close_confirm_ok_text' |
  'modal-generate_close_confirm_title' |
  'modal-generating_title' |
  'modal-ok_text' |
  'settings-fps' |
  'settings-platform' |
  'settings-speed' |
  'settings-video_height' |
  'settings-video_width' |
  'status-current_audio_name_label' |
  'status-current_file_name_label' |
  'status-current_in_queue' |
  'status-current_map_name_label' |
  'status-current_settings' |
  'status-current_status' |
  'status-current_warning_audio_not_match' |
  'status-current_warning_label' |
  'status-current_warning_replay_not_match' |
  'status-download_button' |
  'status-generate_generating_introduction' |
  'status-generate_progress_label' |
  'status-generate_status_error' |
  'status-generate_status_finish' |
  'status-generate_status_processing' |
  'status-generate_status_queue' |
  'status-generate_status_unknown' |
  'status-generate_success'
;
