import { TI18nKeys } from './types';

const resource: Record<TI18nKeys, string> = {
  'app-title': '骂娘渲染器',
  'current-language': '简体中文',
  'app-settings': '设置',
  'settings-fps': 'FPS',
  'settings-platform': '平台',
  'settings-speed': '下落速度（像素/帧）',
  'settings-video_height': '视频宽度',
  'settings-video_width': '视频高度',
  'main-upload_replay_placeholder': '拖动或点击此处上传回放文件',
  'main-upload_map': '拖动或点击此处上传谱面、谱包文件',
  'main-upload_bgm': '拖动或点击此处上传 bgm 文件',
  'main-upload_replay_placeholder_hint': '支持 .osr, .mr 文件',
  'main-upload_map_hint': '支持 .osz, .osu, .mcz, .mc, .zip文件',
  'main-upload_bgm_hint': '支持所有的 osu 或 malody 支持的音频文件',
  'main-drag_upload_text': '拖动或点击此处上传',
  'modal-error_title': '错误！',
  'modal-error_file_size_over_max': '文件大小不能超过 25M !',
  'modal-ok_text': '确认',
  'upload-modal_title': '正在生成...',
  'btn-generate': '一键生成！',
  'status-current_status': '当前状态：',
  'status-current_in_queue': '当前排队数量',
  'status-generate_success': '生成成功！您可以点击下载了',
  'status-download_button': '这就下载!',
  'status-generate_progress_label': '当前进度',
  'status-generate_status_finish': '已完成',
  'status-generate_status_unknown': '等待中',
  'status-generate_status_queue': '排队中',
  'status-generate_status_processing': '处理中',
  'status-generate_generating_introduction': '**正在生成，请不要关闭窗口或浏览器**',
  'modal-generate_close_confirm_title': '您确定要关闭吗？',
  'modal-generate_close_confirm_content': '关闭窗口将会停止生成回放视频，您确定要关闭吗？',
  'modal-generate_close_confirm_ok_text': '确定',
  'modal-generate_close_confirm_cancel_text': '取消',
};

export const zh = {
  translation: resource,
};
